services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: calendar-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: calendar_app_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calendar-app-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: calendar_app_dev
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SSL: false
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: dev

volumes:
  postgres_data:
